version: "2.3"
services:
  rank0:
    image: pytorch-distributed-example
    networks:
      bridge:
        ipv4_address: 10.1.0.10
    command: python3 -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=0 --master_addr="10.1.0.10" --master_port=1234 main.py
  rank1:
    image: pytorch-distributed-example
    networks:
      bridge:
        ipv4_address: 10.1.0.11
    command: python3 -m torch.distributed.launch --nproc_per_node=1 --nnodes=2 --node_rank=1 --master_addr="10.1.0.10" --master_port=1234 main.py
networks:
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 10.1.0.0/16
